services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stackbridge-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - stackbridge-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stackbridge-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - stackbridge-network

  db:
    image: postgres:15
    container_name: stackbridge-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: stackbridge
    ports:
      - "5432:5432"
    volumes:
      - stackbridge-volume:/var/lib/postgresql/data
    networks:
      - stackbridge-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  stackbridge-volume:

networks:
  stackbridge-network:
