kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-pvc
  namespace: stackbridge-lab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
