kind: Secret
apiVersion: v1
metadata:
  name: db-secret
  namespace: stackbridge-lab
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_PASSWORD: c3RhY2ticmlkZ2VAMTIz  # base64 of 'stackbridge@123'
