kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: stackbridge
nodes:
  - role: control-plane
    image: kindest/node:v1.31.2
    extraPortMappings:
      - containerPort: 32000
        hostPort: 32000
        protocol: TCP
      - containerPort: 32001
        hostPort: 32001
        protocol: TCP
  - role: worker
    image: kindest/node:v1.31.2
  - role: worker
    image: kindest/node:v1.31.2
  - role: worker
    image: kindest/node:v1.31.2
